version: '3.7'
services:
  react:
    container_name: drive-moto
    image: 'drive-moto:latest'
    restart: unless-stopped
    build: .
    ports:
      - '8081:443'
    networks:
      - default

networks:
  default:
    external: true
    name: sklyarv