import { cardProps } from "../components/cards/cardsContent/cardProps";
import oftenBuy1 from "../assets/img/main/oftenBuy1.png";
import oftenBuy2 from "../assets/img/main/oftenBuy2.png";
import oftenBuy3 from "../assets/img/main/oftenBuy3.png";
import oftenBuy4 from "../assets/img/main/oftenBuy4.png";

export const oftenBuyList: cardProps[] = [
  {
    title: "BRP Audio-портативная система",
    price: 0,
    actions: [],
    isInInventory: false,
    brandId: "",
    countryId: "",
    id: "0",
    img: oftenBuy1,
    isFavourite: false,
    isOnRequest: false,
    modelId: "",
  },
  {
    title: "Garmin Echomap Plus 62cv",
    price: 45800,
    actions: [],
    isInInventory: true,
    brandId: "",
    countryId: "",
    id: "1",
    img: oftenBuy2,
    isFavourite: false,
    isOnRequest: false,
    modelId: "",
  },
  {
    title: "RF D.E.S.S.TM Key",
    price: 0,
    actions: [],
    isInInventory: false,
    brandId: "",
    countryId: "",
    id: "2",
    img: oftenBuy3,
    isFavourite: false,
    isOnRequest: false,
    modelId: "",
  },
  {
    title: "Мужской костюм\n3мм",
    price: 7000,
    actions: [],
    isInInventory: true,
    brandId: "",
    countryId: "",
    id: "3",
    img: oftenBuy4,
    isFavourite: false,
    isOnRequest: false,
    modelId: "",
  },
  {
    title: "Garmin Echomap Plus 62cv",
    price: 45800,
    actions: [],
    isInInventory: true,
    brandId: "",
    countryId: "",
    id: "4",
    img: oftenBuy2,
    isFavourite: false,
    isOnRequest: false,
    modelId: "",
  },
  {
    title: "BRP Audio-портативная система",
    price: 0,
    actions: [],
    isInInventory: false,
    brandId: "",
    countryId: "",
    id: "5",
    img: oftenBuy1,
    isFavourite: false,
    isOnRequest: false,
    modelId: "",
  },
  {
    title: "Мужской костюм\n3мм",
    price: 7000,
    actions: [],
    isInInventory: true,
    brandId: "",
    countryId: "",
    id: "6",
    img: oftenBuy4,
    isFavourite: false,
    isOnRequest: false,
    modelId: "",
  },
  {
    title: "RF D.E.S.S.TM Key",
    price: 0,
    actions: [],
    isInInventory: false,
    brandId: "",
    countryId: "",
    id: "7",
    img: oftenBuy3,
    isFavourite: false,
    isOnRequest: false,
    modelId: "",
  },
];
